name: Build All Platforms

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: '请输入本次版本的更新说明 (将自动展示在 Release 页面中)'
        required: false
        default: '修复底层插件之间 API 版本冲突引发的打包失败'

jobs:
  call-private-build:
    uses: chinaxsir/Xsop-Client-Workflows/.github/workflows/Client_build.yml@main
    with:
      release_notes: ${{ github.event.inputs.release_notes }}
    secrets: inherit
